// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iswyykbducijzapdkwdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzd3l5a2JkdWNpanphcGRrd2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjA3NDgsImV4cCI6MjA2ODU5Njc0OH0.LdOgop8quKdhTPJrxty55EsTBaFnI05ILvQPwq5y0DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});